### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by vilesis** [dana-at-cp/backdoor-apk#169]
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - APKPure

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.NoSuchMethodError: brut.androlib.meta.StringExConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
        at brut.androlib.meta.StringExConstructor.access$100(StringExConstructor.java:25)
        at brut.androlib.meta.StringExConstructor$ConstructStringEx.construct(StringExConstructor.java:32)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
        at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:85)
        at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:70)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:190)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
        at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:262)
        at brut.androlib.Androlib.build(Androlib.java:276)
        at brut.androlib.Androlib.build(Androlib.java:269)
        at brut.apktool.Main.cmdBuild(Main.java:247)
        at brut.apktool.Main.main(Main.java:79)

```

**Comment by dana-at-cp** [comment]
Try another APK, like the APKs that are distributed with backdoor-apk.

Also, try APKs from the Google Play Store. Can't support every APK in existence and definitely not APKs from third-party app stores.
