### ISSUE TITLE
Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by majid-d** [dana-at-cp/backdoor-apk#176]
"Failed to recompile original project with backdoor"
Stuck at this process, i have tried with other .apk files but no success
using Parrot OS the latest version on virtual box
am i the only one confronting with this issue ?

**Comment by yeguangxiadedaya** [comment]
hello,i had the same issue with that process?,i don't know how to do ,please tell me if you knew already.thanks

**Comment by sindikto** [comment]
oh my friend, no I am with this problem too,
I've kali  19 roling and  probe diferent options and nothing to do
if you know how do it please write me, thanks.

**Comment by Alexandre-ux** [comment]
Devem instalar zipalign.
sudo apt-get install zipalign

**Comment by frostKn** [comment]
> Devem instalar zipalign.
> sudo apt-get install zipalign

that doesn't solve the problem for me .... normal decompile and recompile works just fine
I tried changing the apktools.jar
zipalign is installed 
installed lib32ncurses5
changed to java 8
no luck yet.
__________________
this is the run.log error
___________________

> invoke-static {}, Lcom/snaptube/premium/gjqzy/Jlwfr;->start()V
The smali file was hooked successfully
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/support/v4/util/LongSparseArray;->clone()Landroid/support/v4/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418)
	at brut.androlib.Androlib.buildSources(Androlib.java:349)
	at brut.androlib.Androlib.build(Androlib.java:301)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:251)
	at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x13
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65537
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
	... 11 more

Forcing cleanup due to a failure or error state!

**Comment by frostKn** [comment]
Alright here is how I fixed the error :
first, check if these r installed

>ib32z1 lib32ncurses5 lib32stdc++6

then,

> apt-get purge apktool

and now we will install it manually
go to [https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool](url) and copy everything to a blank file and name it apktool

now give it permissions by 

> chmod +x apktool

download the latest apktool from here [https://bitbucket.org/iBotPeaches/apktool/downloads/](url) and rename it apktool.jar 

give it permissions 

> chmod +x apktool.jar

now move both of them to /usr/local/bin

> sudo mv apktool /usr/local/bin && sudo mv apktool.jar /usr/local/bin

now apktool in terminal and see if it works.

i am using java11 with no issues but if r still having problems try changing it to java8 by

> update-alternatives --config java

**Comment by ghost** [comment]
chmod +x  apktool_2.4.1.jar

**Comment by dana-at-cp** [comment]
Always use the latest version of Apktool.
