### ISSUE TITLE
jarsigner error: java.lang.RuntimeException: certificate exception: Empty issuer DN not allowed in X509Certificates

### ISSUE THREAD

**Issue by iSapron** [dana-at-cp/backdoor-apk#34]
This bug appeared with the latest version of the script (15 hours ago). I don't know, what i have to do.
#14 
//sorry for my bad English, i'm from Russia ;-)

**Comment by iSapron** [comment]
Sorry, it's apk error, i just try with another apk and it's output this mistake:
I: Using Apktool 2.2.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
original/smali/mobi/wrt/android/smartcontacts/app/MainActivity.smali[1285,4] Invalid register: v22. Must be between v0 and v15, inclusive.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: mobi/wrt/android/smartcontacts/app/MainActivity.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:67)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:51)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:400)
	at brut.androlib.Androlib.buildSources(Androlib.java:331)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Forcing cleanup due to a failure or error state!
Help me :0

**Comment by iSapron** [comment]
i'm very sorry, it's again apk error, i took the apk baidu-browser and it has work!!! The last question: can i install the backdoor into a dialer's apk? Thanks in advance!

**Comment by dana-at-cp** [comment]
Generally, Apktool only chokes on an APK when the APK itself has deficiencies or is otherwise malformed. You will see these types of issues with random APKs on the Internet but are less likely to have issues with legitimate APKs that are obtained via the Google Play Store.

To answer your question: Theoretically, you can backdoor any APK that doesn't have any issues identified by Apktool. :)
