### ISSUE TITLE
Failed to decompile RAT APK file

### ISSUE THREAD

**Issue by samuelmwai** [dana-at-cp/backdoor-apk#44]
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 192.168.x.x:4444
[*] Decompiling RAT APK file...done.
[!] Failed to decompile RAT APK file

Hi, it fails to decompile and throws the attached error. Below is an extract of the run.log file

No encoder or badchars specified, outputting raw payload
Payload size: 9310 bytes
Saved as: Rat.apk
 16:49:08 up 1 day,  2:02,  1 user,  load average: 0.26, 0.25, 0.23
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     tty2     :1               Thu17   23:02m  6:01m  5:26m firefox-esr
I: Using Apktool 2.0.2-dirty on Rat.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000001
I: Loading resource table from file: /root/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000011
I: Loading resource table from file: /root/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000001
I: Loading resource table from file: /root/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000011
Exception in thread "main" java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
	at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:199)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:100)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Forcing cleanup due to a failure or error state!
[run.log.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/516300/run.log.tar.gz)

**Comment by userdsp** [comment]
Update your Apktool version.

**Comment by samuelmwai** [comment]
I have cloned the apk tool from the latest branch. Still experiencing same error. Have tried with a few apks sourced from Apk4fun. Attached is the run log file
[run.log.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/533924/run.log.tar.gz)
The required lib files i.e. lib32stdc++6 lib32ncurses5 lib32z1 are also upto to date. Refer screenshot
[Lib.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/533943/Lib.tar.gz)

**Comment by dana-at-cp** [comment]
@samuelmwai I suspect that this is an issue with the APK file itself. Try using a legitimate APK from the Google Play store.

**Comment by samuelmwai** [comment]
I had not looked at this. Let me give it a shot. Thank you for the link.

**Comment by samuelmwai** [comment]
Hi Dana,

I have managed. I had not set the Java environment correctly. I followed this link https://ibotpeaches.github.io/Apktool/install/ as well as https://www.blackmoreops.com/2015/08/15/how-to-install-java-in-kali-linux-2-0-kali-sana/. The Apk to be used is also a factor to consider as i have tried with two Apks. One from Google-play and the other from apk4fun. I have documented the errors in the attached doc
[apkerrors.tar.gz](https://github.com/dana-at-cp/backdoor-apk/files/534516/apkerrors.tar.gz)

Thanks a lot. Works like charm
Warm regards,
Sam

**Comment by dana-at-cp** [comment]
@samuelmwai Awesome! You will have better luck with APKs you obtain from the play store.

**Comment by anonymouskillerbr1** [comment]
Hello have you tried using the backdoor-apk and have data the next error, [!] Failed to generate RAT APK file. I've already put the original APK in the backdoor-apk folder, backdoor-apk, and even then the error that I showed above, how can I fix this?
